### ISSUE TITLE
pisa name exists in PyPI

### ISSUE THREAD

**Issue by jllanfranchi** [icecube/pisa#126] opened 2016-08-31 17:17 UTC
Can cause confusion, installation issues; the description certainly isn't confusing, but how to proceed may be. Can we come up with a different package name that gets referenced in the pip database? I have no idea how this works...

``` bash
$ pip search pisa
pisa (3.0.33)                                  - PDF generator using HTML and CSS
```

**Comment by LeanderFischer** [comment] 2023-06-09 07:23
The problem is being tackled via https://github.com/pypi/support/issues/2813.

**Comment by LeanderFischer** [comment] 2023-06-09 07:25
Wow, this issue is from 2016 omg.

**Comment by LeanderFischer** [comment] 2024-08-15 09:39
Moved into [active processing a few weeks ago](https://github.com/pypi/support/issues/2813) :tada:

**Comment by LeanderFischer** [comment] 2024-11-18 07:21
Closing since https://github.com/pypi/support/issues/2813 is successfully completed now.

**Closed by LeanderFischer** 2024-11-18 07:21 UTC
Labels: enhancement, question, usability
